

add_executable(0276A 0276A.cpp)

add_executable(1872 1872.cpp)

add_executable(1330a 1330a.cpp) 

add_executable(1352A_2 1352A_2.cpp)
add_executable(1352A 1352A.cpp) 

add_executable(339B 339B.cpp)

add_executable(1670B 1670B.cpp) 

add_executable(1873c 1873c.cpp)
add_executable(1873cm 1873cm.cpp)
add_executable(1873d 1873d.cpp)